- name: Install CUDA Python examples
  hosts: python
  tasks:
    - name: Update Apt cache and upgrade Apt packages
      apt:
        autoremove: yes
        update_cache: yes
        upgrade: yes
      become: yes
    - name: Install CUDA toolkit
      apt:
        name: nvidia-cuda-toolkit
        state: latest
      become: yes
    - name: Install Python Apt packages
      apt:
        name:
          - python3.9
          - python3-pip
          - python3.9-venv
        state: latest
      become: yes
    - name: Install Poetry
      pip:
        executable: pip3
        name: poetry
    - name: Copy Python code
      copy:
        src: ./
        dest: "{{ ansible_env.HOME }}/python"
    - name: Install code Python dependencies
      environment:
        PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
      shell:
        chdir: "{{ ansible_env.HOME }}/python"
        cmd: |
          python3.9 -m venv .venv
          .venv/bin/pip install -upgrade pip wheel
          poetry config virtualenvs.in-project true
          poetry install
        executable: /bin/bash
